allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import datetime
from storage import FSS

from allauth.account.signals import user_signed_up
from django.dispatch import receiver

from dbmail import send_db_sms, send_db_mail


store = FSS()

MONTHS = (
    ('01', 'Январь'),
    ('02', 'Февраль'),
    ('03', 'Март'),
    ('04', 'Апрель'),
    ('05', 'Май'),
    ('06', 'Июнь'),
    ('07', 'Июль'),
    ('08', 'Август'),
    ('09', 'Сентябрь'),
    ('10', 'Октябрь'),
    ('11', 'Ноябрь'),
    ('12', 'Декабрь'),
)

FAMILY = (
    ('yes', "Женат\Замужем"),
    ('no', "Холост\Не замужем")
)


class Area(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True)
    parent_id = models.IntegerField(null=True)
    area = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.area
    
    class Meta:
        ordering = ('area',)
        
class Metro(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True)
    name = models.CharField(null=True, max_length=255)
    area = models.ForeignKey(Area)
    
    def __unicode__(self):
        return self.name


class Citizenship(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True)
    citizenship = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.citizenship
      
    class Meta:
        ordering = ('citizenship',)

class DocumentType(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True)
    document = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.document
    
    class Meta:
        ordering = ('document',)


class KnownFrom(models.Model):
    
    choice = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.choice


class Profile(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    f_name = models.CharField(blank=True, max_length=30)
    m_name = models.CharField(blank=True, max_length=30)
    l_name = models.CharField(blank=True, max_length=30)
    bd_day = models.CharField(blank=True, max_length=2)
    bd_month = models.CharField(blank=True, choices=MONTHS, max_length=2)
    bd_year = models.CharField(blank=True, max_length=4)
    doc_type = models.ForeignKey(DocumentType, null=True, blank=True, default=1)
    pass_series = models.CharField(null=True, blank=True, max_length=20)
    pass_number = models.CharField(null=True, blank=True, max_length=20)
    issued_by = models.CharField(null=True, blank=True, max_length=255)
    issued_date = models.DateField(null=True, blank=True)
    sub_code = models.CharField(null=True, blank=True, max_length=10)
    birth_place = models.CharField(null=True, blank=True, max_length=255)
    citizenship = models.ForeignKey(Citizenship, null=True, blank=True)
    pass_reg_place = models.CharField(null=True, blank=True, max_length=255)
    curr_reg_place = models.CharField(null=True, blank=True, max_length=255)
    temp_reg = models.BooleanField(default=False)
    temp_reg_date = models.DateField(null=True, blank=True)
    temp_reg_last_date = models.DateField(null=True, blank=True)
    inn = models.BigIntegerField(null=True, blank=True)
    area = models.ForeignKey(Area, null=True, blank=True)
    metro = models.ForeignKey(Metro, null=True, blank=True)
    phone = models.CharField(null=True, blank=True, max_length=20)
    experience = models.TextField(null=True, blank=True)
    family = models.CharField(null=True, blank=True, choices=FAMILY, max_length=3)
    children = models.BooleanField(default=False)
    child_age_old = models.IntegerField(null=True, blank=True)
    child_age_jr = models.IntegerField(null=True, blank=True)
    web_edu = models.BooleanField(default=False)
    ru_card = models.BooleanField(default=False)
    med_book = models.BooleanField(default=False)
    mb_date = models.DateField(null=True, blank=True)
    mb_city = models.CharField(null=True, blank=True, max_length=25)
    med_exam_date = models.DateField(null=True, blank=True)
    mb_desc = models.CharField(null=True, blank=True, max_length=25)
    disability = models.BooleanField(default=False)
    disability_group = models.IntegerField(null=True, blank=True)
    infect = models.BooleanField(default=False)
    known_from_list = models.ForeignKey(KnownFrom, null=True, blank=True)
    known_from = models.TextField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    badge_id = models.CharField(blank=True, null=True, max_length=25)
    avatar = models.ImageField(upload_to='avatars/', blank = True, default='/static/img/avatars/d_av.png', storage=store)
    filled = models.BooleanField(default=False)
    modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return self.user.username
    
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
            Notification.objects.create(user = instance, text = "Добро пожаловать в сообщество Лидер Тим! Регистрация прошла успешно!")

    post_save.connect(create_user_profile, sender=User)

from jobs.models import Notification
@receiver(user_signed_up, dispatch_uid="registration")
def user_signed_up_(request, user, **kwargs):
    user_phone = request.POST.get('phone')
    user_mail = request.POST.get('email')
    recipient = str(user_phone[0:2] + user_phone[4:7] + user_phone[9:12] + user_phone[13:15] + user_phone[16:18])
    send_db_sms(slug="reg_sms", recipient = recipient, use_celery=False)
    send_db_mail(slug="reg_mail", recipient = user_mail, use_celery=False)

users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Profile



class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = ('user',)

users/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from models import Profile, Area, Citizenship, DocumentType, Metro
from forms import ProfileForm
import lthh.settings as settings
import os, re, base64, tempfile
from django.core.files import File
from django.core import serializers
from django.forms.models import model_to_dict
import json as simplejson


@login_required
def profile(request):
    p = get_object_or_404(Profile, user=request.user)
    reg = Area.objects.all()
    ctz = Citizenship.objects.all()
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = p.user
            profile.filled = True
            profile.badge_id = p.badge_id
            profile.status = p.status
            profile.save()
            return JsonResponse({'status':'saved'})
    #else:
        #profile_form = ProfileForm(instance = Profile.objects.get(user_id=request.user.id))
    #return JsonResponse({'status':'loaded'})

@login_required
def edit(request):
    p = get_object_or_404(Profile, user=request.user)
    reg = Area.objects.all()
    ctz = Citizenship.objects.all()
    doc = DocumentType.objects.all()
    if request.method == 'POST':
        dt = 0
        profile_form = ProfileForm(request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            if request.POST.get('u_avatar'):
                dt = 1
                sp = os.path.join(settings.MEDIA_ROOT, 'avatars', request.user.username + "_avatar.jpg")
                dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
                ImageData = request.POST.get('u_avatar')
                ImageData = dataUrlPattern.match(ImageData).group(2)
                ImageData = base64.b64decode(ImageData)
                ava = tempfile.TemporaryFile()
                av = File(ava)
                av.write(ImageData)
                av.name = request.user.username + "_avatar.jpg"
                profile.avatar = av
            else:
                profile.avatar = p.avatar
            profile.user = p.user
            if (request.POST.get('f_name')
                and request.POST.get('l_name')
                and request.POST.get('bd_day')
                and request.POST.get('bd_month')
                and request.POST.get('bd_year')
                and request.POST.get('phone')):
                profile.filled = True
            else:
                profile.filled = False
            profile.badge_id = p.badge_id
            profile.status = p.status
            profile.save()
            if dt == 1:
                ava.close()
            return HttpResponseRedirect('jobs')
    else:
        profile_form = ProfileForm(instance = Profile.objects.get(user_id=request.user.id))
    return render(request, 'edit.html', {'profile_form' : profile_form, 'region' : reg, 'citiz' : ctz, 'doc' : doc})

def metro_list(request, regid):
    if request.is_ajax():
        regions = Metro.objects.distinct('area')
        metros = Metro.objects.filter(area=regid).order_by('name')
        mlist = []
        for m in metros:
            metro = {}
            metro['id'] = m.id
            metro['name'] = m.name
            mlist.append(metro)
        out = simplejson.dumps(mlist)
        return HttpResponse(out, content_type="application/json")

users/templates/edit.html
{% extends "basis.html" %}
{% load l10n %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load user_aid %}

{% block extend_header %}
<link href="{% static 'dp/daterangepicker.min.css' %}" rel="stylesheet">

<link href="{% static 'css/transition.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

<script src="{% static 'dp/moment.js' %}"></script>
<script src="{% static 'dp/daterangepicker.js' %}"></script>
<script src="{% static 'js/cropit.js' %}"></script>
<script src="{% static 'js/date.js' %}"></script>

<script src="{% static 'js/validation.js' %}"></script>

<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}
{% block content %}
<div id="profile_container" class="container">
  <form id="profile_form" class="ui form" method="POST">
  {% csrf_token %}
    <div class="b-quest mrg">
      {{ profile_form.errors }}
    </div>
    <div class="b-quest-form">
    <div class="row">
        <div class="col-md-9">
        <div class="b-quest__header">
            <div class="b-quest__name">
                {{ request.user.profile.l_name}} {{ request.user.profile.f_name}} {{ request.user.profile.m_name}}
            </div>
        </div>
        <div class="form-name row fields">
            <div class="field">
                <input id="id_l_name" maxlength="30" name="l_name" type="text" placeholder="Фамилия" value="{{ request.user.profile.l_name}}"/>
            </div>
            <div class="field">
                <input id="id_f_name" maxlength="30" name="f_name" type="text" placeholder="Имя" value="{{ request.user.profile.f_name}}"/>
            </div>
            <div class="field">
                <input id="id_m_name" maxlength="30" name="m_name" type="text"placeholder="Отчество" value="{{ request.user.profile.m_name}}"/>
            </div>
        </div>
            <div class="field">
                <label class="label-head label-head--inline">
                    <span>Дата рождения:</span>
                </label>
            </div>
          <div id="birth_date" class="fields"> 
            <div class="two wide field">
                <input id="id_bd_day" maxlength="2" name="bd_day" type="text" placeholder="День" value="{{ request.user.profile.bd_day}}"></input>
            </div>
            <div class="four wide field">
              {{ profile_form.bd_month|add_class:"ui dropdown"}}
            </div>
            <div class="two wide field">
              <input id="id_bd_year" maxlength="4" name="bd_year" type="text" placeholder="Год" value="{{ request.user.profile.bd_year}}"></input>
            </div>
          </div>
          <div id="date_check">
             <div class="ui basic red pointing prompt label">Введите корректную дату! (День Месяц Год)</div>
          </div>
         </div>       
        </div>
        <hr class="hr-dotted"/>
        <div class="form-inline form-passport-id">
            <div class="form-group">
                    <label class="label-sub-head label-sub-head--inline">
                        <span>Гражданство</span>
                    </label>
            </div>
             <div class="form-group">
                <div class="form-stretched__cell form-stretched__cell--value">
                    {{ profile_form.citizenship|add_class:"custom-select custom-select--width-month selectpicker ui search selection dropdown"}}
                </div>
            </div>
        </div>
        <div class="form-inline form-passport-id">
           <input id="reg_check" type="hidden" value="{{ request.user.profile.area.id }}"/>
           <input id="met_check" type="hidden" value="{{ request.user.profile.metro.id }}"/>
          <div class="form-group">
                <label class="label-sub-head label-sub-head--inline label-sub-head--reg">
                    <span>Регион</span>
                </label>
            </div>
            <div class="form-group">
                <div class="form-stretched__cell form-stretched__cell--value">
                    {{ profile_form.area|add_class:"custom-select custom-select--width-month selectpicker ui search selection dropdown"}}
                    <script type="text/javascript">
                         $('#id_area').val("{% user_aid %}");
                    </script>
              </div>
            </div>
        </div>
        <hr class="hr-dotted"/>
        <div class="label-head">
            <span>Тел. Мобильный:</span>
        </div>
        <div class="form-inline form-mobile-phone field">
            <div class="form-group">
                <input id="id_phone" class="form-control custom-form-control" maxlength="20" name="phone" type="text" placeholder="+7 (___) ___-__-__" value="{{ request.user.profile.phone}}"></input>
            </div>
        </div>
        <hr class="hr-dotted"/>
        <div class="label-head">
            <span>Пожелания к работе:</span>
        </div>
        <div class="field">
           <textarea rows="5" id="id_experience" placeholder="Описание" name="experience">{% if request.user.profile.experience %}{{ request.user.profile.experience }}{% endif %}</textarea>
        </div>
        <hr class="hr-dotted"/>
        {% if request.user.profile.filled %}
        {% else %}
            <input type="submit" id="edit_submit" class="btn btn-form btn-block" value="Внести изменения">
        {% endif %}
    </div>  
  </form>
</div>
{% include "validation_modal.html" %}
{% endblock %}

{% block scripts %}


{% endblock %}

users/templates/profile.html
{% extends "basis.html" %}
{% load staticfiles %}

{% block content %}
<div class="ui padded grid">
    <div class="sixteen wide column">
        <div id="profile_cont" class="ui segment grid">
            <div class="three wide column">
                <img class="ui small rounded image" src="{{ request.user.profile.avatar.url}}"></img>
            </div>
            {% if request.user.profile.filled %}
            <div class="thirteen wide column">
                <h3>{{ request.user.profile.l_name}} {{ request.user.profile.f_name}} {{ request.user.profile.m_name}}</h3>
                <div class="ui divider"></div>
                <p>{{ request.user.profile.bd_day }}.{{ request.user.profile.bd_month }}.{{ request.user.profile.bd_year }}</p>
                {% if request.user.profile.area %}
                    <p>{{ request.user.profile.area }}</p>
                {% endif %}
                <p>{{ request.user.profile.phone }}</p>
                <p>{{ request.user.profile.about }}</p>
            </div>
            {% else %}
            <div class="thirteen wide center aligned column">
                <h2 class="ui red header">Ваш профиль совсем пустой. Любая активность недоступна. Пожалуйста, заполните его.</h2>
            </div>
            {% endif %}
            <div class="sixteen wide center aligned column">
                <a href="/edit" class="ui small primary button">Редактировать</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/validation_modal.html
<div class="modal fade" id="profile_modal" tabindex="-1" role="dialog" aria-labelledby="profile_modal_label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Вы не заполнили обязательные поля!</h4>
      </div>
      <div class="modal-body">
          Обязательными полями являются:
          <ul>
              <li>Фамилия и имя</li>
              <li>Дата рождения</li>
              <li>Номер телефона</li>
          </ul>
          Если эти поля останутся пустыми, функциональность на сайте будет ограничена.
          <p>
              Продолжить сохранение профиля с незаполненными полями?
          </p>
      </div>
      <div class="modal-footer">
        <button id="req_cancel" type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
        <button id="req_submit" type="button" class="btn btn-primary" data-dismiss="modal">Да</button>
      </div>
    </div>
  </div>
</div>