allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

interview/models.py
# -*- coding: utf-8 -*-
from django.db import models
from users.models import Area
import time


class ProdCalendar(models.Model):
    date = models.DateField(unique=True, null=False, primary_key=True, default = '1900-01-01')
    week_day = models.IntegerField()
    day_type = models.CharField(max_length = 1)
    
    def __unicode__(self):
        return self.date.strftime('%Y-%m-%d')
    
    class Meta:
        ordering = ('date',)
        
        
class Office(models.Model):
    address = models.TextField(null=True, blank=True)
    w1o = models.TimeField(null=True, blank=True, default="09:30")
    w1c = models.TimeField(null=True, blank=True, default="18:00")
    w2o = models.TimeField(null=True, blank=True, default="09:30")
    w2c = models.TimeField(null=True, blank=True, default="18:00")
    w3o = models.TimeField(null=True, blank=True, default="09:30")
    w3c = models.TimeField(null=True, blank=True, default="18:00")
    w4o = models.TimeField(null=True, blank=True, default="09:30")
    w4c = models.TimeField(null=True, blank=True, default="18:00")
    w5o = models.TimeField(null=True, blank=True, default="09:30")
    w5c = models.TimeField(null=True, blank=True, default="18:00")
    interval = models.IntegerField(null=True, blank=True)
    managers = models.IntegerField(null=True, blank=True)
    schedule = models.CharField(null=True, blank=True, max_length = 90)
    email = models.CharField(null=True, blank=True, max_length = 90)
    city = models.CharField(null=True, blank=True, max_length = 90)
    phone = models.CharField(null=True, blank=True, max_length = 90)
    map_id = models.CharField(null=True, blank=True, max_length = 255)
    
    def __unicode__(self):
        return self.city

    
class CitiesByArea(models.Model):
    cid = models.ForeignKey(Office)
    aid = models.ForeignKey(Area)
    
    def __unicode__(self):
        return self.aid.area


class OfficeCalendar(models.Model):
    oid = models.ForeignKey(Office)
    date = models.DateField()
    wo = models.TimeField()
    wc = models.TimeField(null=True)

    def __unicode__(self):
        return self.date.strftime('%Y-%m-%d')

interview/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Office


class OfficeForm(forms.ModelForm):

    class Meta:
        model = Office
        exclude = ('id', )

interview/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from models import ProdCalendar, Office, OfficeCalendar
from forms import OfficeForm
from users.models import Area
from prodcalparser import ProdCalParser
import datetime
from datetime import date
from django.core import serializers
import json as simplejson

BASE_URL = 'http://www.superjob.ru/proizvodstvennyj_kalendar/'

def design_demo(request):
    return render(request, 'index.html',)

def pc_update(request):
    u = request.user
    try:
        oid = CitiesByArea.objects.get(aid = u.profile.area.id)
    except:
        oid = 666
    curr_year = date.today().year
    cal = ProdCalendar.objects.all()
    out = []
    officies = Office.objects.all()
    if request.method == 'POST':
        if 'year' in request.POST:
            year = request.POST.get("year", "")
            s = ProdCalParser(BASE_URL, year)
            pre_calendar = s.serialize()
            ProdCalendar.objects.filter(date__year = year).delete()
            for key,value in pre_calendar.items():
                ProdCalendar.objects.create(date = key, week_day = value[1], day_type = value[0])
    for f in cal:
        out.append({'date' : str(f.date), 'wd' : f.week_day, 'dt' : f.day_type})
    data = simplejson.dumps(out)
    of = OfficeForm()
    if request.is_ajax():
        return HttpResponse(data, content_type='application/json')
    else:
        return render(request, 'pc_update.html', { 'cal': cal, 'curr_year' : curr_year, 'officies' : officies, 'oid' : oid, 'of' : of })


def office(request, oid):
    u = request.user
    curr_off = Office.objects.get(id = oid)
    off = serializers.serialize('json', Office.objects.filter(id = oid))
    data = simplejson.dumps(off)
    now = datetime.datetime.now()
    date = str(now.year) + "-" + str(now.month) + "-" + str(now.day)
    dates = ProdCalendar.objects.filter(date__gte = date)
    #dates = ProdCalendar.objects.all()
    if request.is_ajax():
        if request.method == 'GET':
            return HttpResponse(data, content_type='application/json')
        elif request.method == 'POST':
            schedule = Office(
                id=oid,
                name=request.POST.get('name'),
                address=request.POST.get('address'),
                w1o=request.POST.get('w1o'),
                w1c=request.POST.get('w1c'),
                w2o=request.POST.get('w2o'),
                w2c=request.POST.get('w2c'),
                w3o=request.POST.get('w3o'),
                w3c=request.POST.get('w3c'),
                w4o=request.POST.get('w4o'),
                w4c=request.POST.get('w4c'),
                w5o=request.POST.get('w5o'),
                w5c=request.POST.get('w5c'),
                interval=request.POST.get('interval'),
                managers=request.POST.get('managers'),
                )
            schedule.save()
            OfficeCalendar.objects.filter(oid = oid).filter(date__gte = date).delete()
            for d in dates:
                if d.day_type != 'h':
                    if d.week_day == 0:
                        wdo = request.POST.get('w1o')
                        wdc = request.POST.get('w1c')
                    elif d.week_day == 1:
                        wdo = request.POST.get('w2o')
                        wdc = request.POST.get('w2c')
                    elif d.week_day == 2:
                        wdo = request.POST.get('w3o')
                        wdc = request.POST.get('w3c')
                    elif d.week_day == 3:
                        wdo = request.POST.get('w4o')
                        wdc = request.POST.get('w4c')
                    elif d.week_day == 4:
                        wdo = request.POST.get('w5o')
                        wdc = request.POST.get('w5c')
                    OfficeCalendar.objects.create(oid = curr_off, date = d.date, wo = wdo, wc = wdc)
            return HttpResponse(data, content_type='application/json')

def office_create(request):
    dates = ProdCalendar.objects.all()
    if request.is_ajax():
        if request.method == 'POST':
            response_data = {}
            schedule = Office(
                name=request.POST.get('name'),
                address=request.POST.get('address'),
                w1o=request.POST.get('w1o'),
                w1c=request.POST.get('w1c'),
                w2o=request.POST.get('w2o'),
                w2c=request.POST.get('w2c'),
                w3o=request.POST.get('w3o'),
                w3c=request.POST.get('w3c'),
                w4o=request.POST.get('w4o'),
                w4c=request.POST.get('w4c'),
                w5o=request.POST.get('w5o'),
                w5c=request.POST.get('w5c'),
                interval=request.POST.get('interval'),
                managers=request.POST.get('managers'),
                )
            schedule.save()
            for d in dates:
                if d.day_type != 'h':
                    if d.week_day == 0:
                        wdo = request.POST.get('w1o')
                        wdc = request.POST.get('w1c')
                    elif d.week_day == 1:
                        wdo = request.POST.get('w2o')
                        wdc = request.POST.get('w2c')
                    elif d.week_day == 2:
                        wdo = request.POST.get('w3o')
                        wdc = request.POST.get('w3c')
                    elif d.week_day == 3:
                        wdo = request.POST.get('w4o')
                        wdc = request.POST.get('w4c')
                    elif d.week_day == 4:
                        wdo = request.POST.get('w5o')
                        wdc = request.POST.get('w5c')
                    OfficeCalendar.objects.create(oid = schedule, date = d.date, wo = wdo, wc = wdc)
            off = serializers.serialize('json', Office.objects.filter(id = schedule.id))
            data = simplejson.dumps(off)
            return HttpResponse(data, content_type='application/json')

def office_work_days(request, oid):
    owd = serializers.serialize('json', OfficeCalendar.objects.filter(oid=oid))
    if request.is_ajax():
        return HttpResponse(owd, content_type='application/json')


def office_work_day_update(request, oid):
    if request.is_ajax():
        if request.method == 'POST':
            oid = request.POST.get('oid')
            date = request.POST.get('date')
            wou = request.POST.get('wo')
            wcu = request.POST.get('wc')
            odu = OfficeCalendar.objects.filter(oid=oid).filter(date=date)
            odu.update(wo = wou, wc = wcu)
            owd = serializers.serialize('json', OfficeCalendar.objects.filter(oid=oid))
            return HttpResponse(owd, content_type='application/json')

interview/templates/pc_update.html
{% extends "basis.html" %}
{% load staticfiles %}

{% block extend_header %}


<link href="{% static 'interview/css/calendar.css' %}" rel="stylesheet">

<script src="{% static 'interview/js/calendar.js' %}"></script>
<script src="{% static 'interview/js/languages/ru.js' %}"></script>
{% endblock %}

{% block main_content %}
<div class="ui padded grid">
    <div class="sixteen wide column">
        <div  class="ui segment grid">
            <div class="sixteen wide column">
                <h3>Расписание</h3>
                <div class="ui divider"></div>
                <div id="calendar"></div>
                <form id="year_update_form" method="POST" class="ui form">
                    {% csrf_token %}
                    <div class="field">
                        <input type="text" name="year" value="{{ curr_year }}"/>
                    </div>
                    
                    <button type="submit" class="ui small green button">Обновить</button>
                </form>
                <div class="ui divider"></div>
            </div>
            <div class="six wide column">
                <select id="os" class="ui dropdown">
                    <option value="{{ oid.oid.id }}" selected="selected">Выберите офис</option>
                    <option value="666">Создать новый</option>
                    {% for o in officies %}
                        <option value="{{ o.id }}">{{ o.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="sixteen wide column">
                <div id="results"></div>
                <form id="year_update_form" method="POST" class="ui form" action="/pc_update">
                    {% csrf_token %}
                    <div class="six wide field">
                        <label for="id_name">Название:</label>
                        <input id="id_name" maxlength="60" name="name" type="text">
                    </div>
                    <div class="six wide field">
                        <label for="id_address">Адрес:</label>
                        <textarea cols="40" id="id_address" name="address" rows="10"></textarea>
                    </div>
                    <div class="inline fields">
                        <label>Понедельник:</label>
                        <div class="field">
                            <input id="id_w1o" name="w1o" type="text">
                        </div>
                        <div class="field">
                            <input id="id_w1c" name="w1c" type="text">
                        </div>
                    </div>
                    <div class="inline fields">
                        <label>Вторник:</label>
                        <div class="field">
                            <input id="id_w2o" name="w2o" type="text">
                        </div>
                        <div class="field">
                            <input id="id_w2c" name="w2c" type="text">
                        </div>
                    </div>
                    <div class="inline fields">
                        <label>Среда:</label>
                        <div class="field">
                            <input id="id_w3o" name="w3o" type="text">
                        </div>
                        <div class="field">
                            <input id="id_w3c" name="w3c" type="text">
                        </div>
                    </div>
                    <div class="inline fields">
                        <label>Четверг:</label>
                        <div class="field">
                            <input id="id_w4o" name="w4o" type="text">
                        </div>
                        <div class="field">
                            <input id="id_w4c" name="w4c" type="text">
                        </div>
                    </div>
                    <div class="inline fields">
                        <label>Пятница:</label>
                        <div class="field">
                            <input id="id_w5o" name="w5o" type="text">
                            </div>
                        <div class="field">
                            <input id="id_w5c" name="w5c" type="text">
                        </div>
                    </div>
                    <div class="six wide field">
                        <label for="id_interval">Интервал в минутах:</label>
                        <input id="id_interval" name="interval" type="text">
                    </div>
                    <div class="six wide field">
                        <label for="id_managers">Менеджеры:</label>
                        <input id="id_managers" name="managers" type="text">
                    </div>
                    <div class="field">
                        <button id="submit_year_update_form" class="ui small green button">Обновить</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>

<div id="day_change" class="ui small modal">
        <i class="close icon"></i>
        <div class="header">
            Изменить режим работы
        </div>
        <div class="content">
        <div class="description">
            <form id="wdu" class="ui form">
                {% csrf_token %}
                <div class="inline field">
                    <label>Число: </label>
                    <p id="date_change"></p>
                </div>
                <div class="two fields">
                    <div class="field">
                        <label>Время открытия:</label>
                        <input id="wou" type="text" name="wou"/>
                    </div>
                    <div class="field">
                        <label>Время закрытия:</label>
                        <input id="wcu" type="text" name="wcu"/>
                    </div>
                </div>
                <input id="curr_date" type="hidden" name="curr_date"/>
            </form>
        </div>
        </div>
        <div class="actions">
            <div id="wdu_submit"  class="ui green button">Сохранить</div>
        </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'interview/js/date.js' %}"></script>
<script src="{% static 'interview/js/main.js' %}"></script>
{% endblock %}