allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

callback/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from users.models import Area

STATUS = (
    ('1', "Новый"),
    ('2', "В работе"),
    ('3', "Отработан"),
)

class CallbackAdmin(models.Model):
    user = models.ForeignKey(User)
    area = models.ForeignKey(Area)
    email = models.EmailField()
    
    def __unicode__(self):
        return self.user.profile.l_name

class Callback(models.Model):
    requester = models.ForeignKey(User)
    area = models.ForeignKey(Area)
    phone = models.CharField(null=True, blank=True, max_length=20)
    status = models.IntegerField(blank=True, choices=STATUS, default=1)
    comment = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return self.requester.profile.l_name

class CallbackFree(models.Model):
    requester = models.CharField(null=True, blank=True, max_length=64)
    area = models.ForeignKey(Area)
    phone = models.CharField(null=True, blank=True, max_length=20)
    status = models.IntegerField(blank=True, choices=STATUS, default=1)
    comment = models.TextField(blank=True, null=True)
    vac_id = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return self.requester

callback/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Callback
from django.contrib.auth.models import User



class CallbackForm(forms.ModelForm):
    class Meta:
        model = Callback
        exclude = ('requester', 'created', 'modified', 'status')
        

class CCUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

callback/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from models import Callback
from users.models import Area, Profile
from forms import CallbackForm, CCUserForm
from decorators import group_required


def callback(request):
    #u = User.objects.get(pk = request.user.id)
    reg = Area.objects.all()
    if request.method == 'POST':
        call_form = CallbackForm(request.POST)
        if call_form.is_valid():
            call = call_form.save(commit=False)
            call.requester = request.user
            call.status = 1
            call.save()
            return HttpResponseRedirect('callback/success')
    else:
        call_form = CallbackForm(request.POST)
    return render(request, 'callback.html', {'call_form' : call_form, 'off' : reg})

def cb_succ(request):
    return render(request, 'callback_success.html', {})
    
@group_required('CC')
def cb_admin(request):
    u = User.objects.get(pk = request.user.id)
    cc_tasks = Callback.objects.all()#filter(area = u.profile.area)
    is_cc_admin = request.user.groups.filter(name__in=['CC_ADMINS', 'ADMINS']).exists()
    is_cc = request.user.groups.filter(name='CC').exists()
    cc_users = request.user.groups.filter(name__in=['CC_ADMINS', 'CC'])
    #cc_tasks = Callback.objects.all()
    if request.method == "POST":
        cc_form = CCUserForm(request.POST)
        if cc_form.is_valid():
            new_user = User.objects.create_user(**cc_form.cleaned_data)
            new_user.save()
            g = Group.objects.get(name='CC')
            g.user_set.add(new_user)
            up = Profile.objects.filter(user = new_user)
            up.update(area = request.user.profile.area)
            up.update(filled = True)
            # redirect, or however you want to get to the main view
            return HttpResponseRedirect('cb_admin')
    else:
        cc_form = CCUserForm()
    return render(request, 'callback_admin.html', {'cc_queue' : cc_tasks, 'is_cc' : is_cc, 'is_cc_admin' : is_cc_admin, 'cc_form' : cc_form, 'cc_users' : cc_users })

def masterzone_calls(request):
    calls = Callback.objects.all().order_by('-created')
    return render(request, 'admin/calls.html', {'calls' : calls })

def masterzone_calls_take(request, cid):
    Callback.objects.filter(id=cid).update(status=2)
    calls = Callback.objects.all().order_by('-created')
    return render(request, 'admin/calls.html', {'calls' : calls })

callback/templates/callback.html
{% extends "basis.html" %}
{% load staticfiles %}

{% block sigreg %}
<div id="fade-screen" class="fade-screen" style="display: block;"></div>
	<div id="call_form" class="">
      <div class="close"><a id="call_form_close" href="javascript:void(0)"><img src="/static/img/popup-close.jpg" alt=""></a></div>
      <div class="title text-center">Обратный звонок</div>
			{% if user.is_authenticated %}
					<form id="call_form" class="ui form" method="POST">
					{% csrf_token %}
						<div class="field">
							  	<label for="id_area">Выберите офис:</label>
                				<select id="id_area" name="area" class="ui dropdown">
                    {% if request.user.profile.area %}
                    <option value="{{ request.user.profile.area.id}}" selected="selected"></option>
                    {% else %}
                    <option value="" selected="selected">---------</option>
                    {% endif %}
                    {% for a in off %}
                    <option value="{{ a.id }}">{{ a.area }}</option>
                    {% endfor %}
                </select>
						</div>
						<div class="field">
							<input class="inp-form" id="id_phone" name="phone" placeholder="E-mail адрес" type="email">
						</div>
							<button class="enter" type="submit">Готово</button>
					</form>
			{% else %}
					<div class="sup-title">Вы не зарегистрированы.</div>
					<button class="enter" onclick="window.location.href='/signup'" type="submit">ЗАРЕГИСТРИРОВАТЬСЯ</button>
			{% endif %}
</div>
{% endblock %}
 {% block content %}
							<section class="section_2">
        <div class="main_title">
          <h1>ПОЛУЧИТЕ ПРЕДЛОЖЕНИЕ О РАБОТЕ <br>ПРЯМО СЕЙЧАС</h1>
        </div>
        <div class="container">
          <div class="row padd">
						<form action="/jobs">
							
						
                <div class="col-md-5 alt-sel">
										 <select class="fancy-select" id="id_position" name="position">
												<option value="" selected="selected">---------</option>
										 </select>
                </div>
                <div class="col-md-5 alt-sel">
                   <select class="fancy-select" id="id_position" name="position">
												<option value="" selected="selected">---------</option>
										 </select>
                </div>
                <div class="col-md-2">
                  <button type="submit" class="search_btn">искать</button>
                </div>
              </form> 
          </div>
          <div class="row text-center">
            <h2 class="top_title_2">Зарегистрируйтесь и получите доступ к 11000 вакансиям</h2>
            <button onclick="window.location.href='/signup/'" class="top_btn_2">Регистрация</button>
          </div>
        </div>

      </section>
<script>
$(document).ready(function(){
		$('body').css('overflow', 'hidden');							
});
</script>
{% endblock %}
<div class="ui padded grid">
    <div class="sixteen wide column">
        <h2 class="ui dividing header">Запрос обратного звонка</h2>
        <form id="call_form" class="ui form grid" method="POST">
            <div class="four wide field">
                <label for="id_area">Выберите офис:</label>
                <select id="id_area" name="area" class="ui dropdown">
                    {% if request.user.profile.area %}
                    <option value="{{ request.user.profile.area.id}}" selected="selected"></option>
                    {% else %}
                    <option value="" selected="selected">---------</option>
                    {% endif %}
                    {% for a in off %}
                    <option value="{{ a.id }}">{{ a.area }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="sixteen wide field">
                <label for="id_comment">Комментарий (опционально):</label> 
                <textarea cols="40" id="id_comment" name="comment" rows="10"></textarea>
            </div>
            <div class="field">
                <button id="call_submit" class="ui small green button">Сохранить</button>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

callback/templates/callback_admin.html
{% extends "basis.html" %}
{% load staticfiles %}

{% block main_content %}
<div class="ui padded grid">
    {% if is_cc_admin or is_cc %}
    <div class="sixteen wide center aligned column">
        <h2 class="ui dividing header">Панель управления звонками</h2>
    </div>
    {% if is_cc_admin %}
    <div class="sixteen wide column">
        
    </div>
    {% endif %}
    <div class="sixteen wide column">
        <table class="ui celled padded striped table">
            <thead>
                <tr>
                    <th>№</th>
                    <th>ФИО</th>
                    <th>Телефон</th>
                    <th>Описание</th>
                    <th>Офис</th>
                    <th>Дата создания</th>
                    <!--<th>Статус</th>-->
                </tr>
            </thead>
            <tbody>
                {% for t in cc_queue %}
                <tr>
                  <td>{{ t.id }}</td>
                  <td>{{ t.requester.profile.f_name }} {{ t.requester.profile.l_name }}</td>
                  <td>{{ t.requester.profile.phone }}</td>
                  <td>{{ t.comment }}</td>
                  <td>{{ t.area }}</td>
                  <td>{{ t.created }}</td>
                  
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="sixteen wide center aligned column">
        У ВАС НЕТ ДОСТУПА
    </div>
    {% endif %}
</div>
{% endblock %}
<td>{{ t.get_status_display }}</td>

<form id="cc_form" class="ui form grid" method="POST">
            <div class="three fields">
                <div class="field">
                    <label for="id_username">Имя пользователя:</label>
                    <input id="id_username" maxlength="30" name="username" type="text">
                    <small>Обязательное поле. Не более 30 символов. Только буквы, цифры и символы @/./+/-/_.</small>
                </div>
                <div class="field">
                    <label for="id_email">Адрес электронной почты:</label>
                    <input id="id_email" maxlength="254" name="email" type="email">
                </div>
                <div class="field">
                    <label for="id_password">Пароль:</label>
                    <input id="id_password" maxlength="128" name="password" type="text">
                </div>
            </div>
            <div class="three fields">
                <div class="six wide field">
                    <label for="id_first_name">Имя:</label>
                    <input id="id_first_name" maxlength="30" name="first_name" type="text">
                </div>
                <div class="six wide field">
                    <label for="id_last_name">Фамилия:</label>
                    <input id="id_last_name" maxlength="30" name="last_name" type="text">
                </div>
                <div class="four wide field">
                    <a id="call_submit" class="ui small green button">Сохранить</a>
                </div>
            </div>
            {% csrf_token %}
        </form>

callback/templates/callback_success.html
{% extends "basis.html" %}
{% load staticfiles %}

{% block main_content %}
<div class="ui padded grid">
    <div class="sixteen wide center aligned column">
        <h2 class="red header">Ваш запрос успешно отправлен. Ожидайте звонка оператора.</h2>
    </div>
</div>
{% endblock %}