allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

jobs/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from users.models import Area


class Position(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True, default = 0)
    position = models.CharField(blank=True, max_length=255)
    image = models.ImageField(upload_to='static/img/positions/', blank = True, default='')
    
    def __unicode__(self):
        return self.position
    
    class Meta:
        ordering = ('position',)


class Shedule(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True, default = 0)
    shedule = models.CharField(blank=True, max_length=255)
    
    def __unicode__(self):
        return self.shedule
        
    class Meta:
        ordering = ('shedule',)


class Vacancy(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True, default = 0)
    position = models.ForeignKey(Position)
    description = models.TextField(blank=True)
    area = models.ForeignKey(Area)
    max_rate = models.PositiveIntegerField()
    min_rate = models.PositiveIntegerField()
    shedule = models.ManyToManyField(Shedule)
    urgent = models.BooleanField(default=False)
    rotational = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return unicode(self.position)


class ReplyStatus(models.Model):
    id = models.IntegerField(unique=True, null=False, primary_key=True, default = 0)
    status = models.CharField(max_length=255)
    
    def __unicode__(self):
        return unicode(self.status)


class Reply(models.Model):
    id = models.AutoField(primary_key=True)
    vacancy = models.ForeignKey(Vacancy)
    user = models.ForeignKey(User)
    status = models.ForeignKey(ReplyStatus, to_field='id')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return unicode(self.vacancy)


class Notification(models.Model):
    user = models.ForeignKey(User)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    new = models.BooleanField(default=True)
    
    def __unicode__(self):
        return unicode(self.text)

jobs/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Reply


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ('vacancy', )

jobs/views.py
# -*- coding: utf-8 -*-
from datetime import datetime
import time
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from models import Vacancy, Shedule, Position, Reply, ReplyStatus, Notification
from users.forms import ProfileForm
from forms import ReplyForm
from users.models import Area, Profile, Citizenship
from filters import JobFilter
import misc
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from functions import user_age, send_warn, send_success
from dbmail import send_db_sms


def all(request):
    age = user_age(request)
    new = ReplyStatus.objects.get(id=0)
    jobs = JobFilter(request.GET, queryset = Vacancy.objects.filter(active=True).order_by('-created'))
    replies = Reply.objects.filter(user = request.user.id).exclude(active = False)
    if request.method == 'POST':
        if request.user.profile.citizenship.id == 643 and age >= 18:
            if replies.count >= 1:
                Reply.objects.filter(user=request.user.id, active=True).update(active=False)
            reply_form = ReplyForm(request.POST)
            if reply_form.is_valid():
                reply = reply_form.save(commit=False)
                reply.user = request.user
                reply.status = new
                reply.save()
                if reply.vacancy.position.id == 292:
                    send_success_custom(request, reply)
                else:
                    send_success(request, reply)
                return HttpResponseRedirect('/replies')
        else:
            time.sleep(10)
            send_warn(request)
            return HttpResponseRedirect('/notifications')
    else:
        reply_form = ReplyForm()
        profile_form = ProfileForm()
    return render(request, 'jobs.html', { 'reply_form' : reply_form, 'replies' : replies, 'jobs' : jobs, 'profile_form' : profile_form })

def job(request, job_id):
    age = user_age(request)
    new = ReplyStatus.objects.get(id=0)
    job = Vacancy.objects.get(id=job_id)
    replies = Reply.objects.filter(user = request.user.id).exclude(active = False)
    if request.method == 'POST':
        if request.user.profile.citizenship.id == 643 and age >= 18:
            reply_form = ReplyForm(request.POST)
            if reply_form.is_valid():
                reply = reply_form.save(commit=False)
                reply.user = request.user
                reply.status = new
                reply.save()
                send_success(request, reply)
                return HttpResponseRedirect('/replies')
        else:
            send_warn(request)
            return HttpResponseRedirect('/notifications')
    else:
        reply_form = ReplyForm()
        profile_form = ProfileForm()
    return render(request, 'job.html', { 'job': job, 'reply_form' : reply_form, 'replies' : replies, 'profile_form' : profile_form })
    
def replies(request):
    replies = Reply.objects.filter(user = request.user.id).order_by('-modified')
    return render(request, 'replies.html', { 'replies': replies,})

def reply_delete(request, rid):
    Reply.objects.filter(id=rid).update(active=False)
    return HttpResponseRedirect('/jobs')

def reply_delete_all(request):
    Reply.objects.filter(user=request.user.id, active=True).update(active=False)
    return HttpResponseRedirect('/jobs')

def notifications(request):
    notifications = Notification.objects.filter(user = request.user.id).order_by('-created')
    response = render(request, 'notifications.html', { 'notifications': notifications,})
    notifications.update(new=False)
    return response

jobs/templates/cancel_modal.html
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Вы уже откликнулись на одну вакансию</h4>
      </div>
      <div class="modal-body">
        Вы уже откликнулись на одну вакансию. Отменить текущую заявку?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Нет</button>
        <button type="button" id="delete_reply" class="btn btn-primary">Да</button>
      </div>
    </div>
  </div>
</div>

jobs/templates/job.html
{% extends "basis.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load user_aid %}

{% block extend_header %}
<script src="{% static 'js/form.js' %}"></script>
<script src="{% static 'js/moment.js' %}"></script>
<script src="{% static 'js/validation.js' %}"></script>

{% endblock %}

{% block content %}
<div class="vac-single-wrap">
  <div class="container">
            <div class="row">
                <div class="col-md-12"><a href="javascript:history.go(-1)" class="return-to">Вернуться к списку вакансий</a></div>
                <div class="col-md-12">
                    <div class="vac-single">
                        <div class="head">
                                <div class="name"><!--<img src="/static/img/vac-list-icon.jpg" alt="">--><span>{{ job.position|upper }}</span></div> 
                                <div class="published">{% if job.urgent %}СРОЧНАЯ{% endif %}</div>
                            </div>
                            <div class="info">
                                <div class="top-info">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="money">
                                                от <strong>{{ job.min_rate }}</strong> до <strong>{{ job.max_rate }}</strong>  за месяц
                                            </div>
                                        </div>
                                        <div class="col-md-3 text-center">
                                            <span>Регион:</span> {{ job.area }}  
                                        </div>
                                    </div>
                                </div> 
                                <div class="schedule">
                                    <span>График работы:</span> {% for s in job.shedule.all %}{{ s }}{% endfor %}
                                </div> 
                                <div class="description">
                                    <span>Описание:</span>
                                    <p>{{ job.description|safe }}</p>
                                </div>
                            </div>
                            <div class="bottom-vac">
                                <div class="col-md-4">
                                    {% if user.is_authenticated %}
                                    <form id="reply_form" method="POST">
                                      {% csrf_token %}
                                        <input id="id_vacancy" type="hidden" name="vacancy" value="{{ job.id }}"/>
                                        {% if not replies.count >= 1 %}
                                        <button type="submit" class="apply" id="for_filled_check_job">Подать заявку</button>
                                        {% else %}
                                        <button type="button" id="cancel" class="apply cancel_modal" data-toggle="modal" data-id="{{ job.id }}" data-target="#myModal">Подать заявку</button>
                                        {% endif %}
                                        {{ reply_form.errors}}
                                    </form>
                                  {% else %}
                                  <h4>Вы должны <a href="/signup/">зарегистрироваться</a> для того, чтобы подать заявку.</h4>
                                  {% endif %}
                                </div>
                                <div class="clear"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
</div>

	{% include "cancel_modal.html" %}
{% endblock %}

{% block scripts %}
		  <script src="{% static 'js/jobs.js' %}"></script>
	{% endblock %}


<div class="ui padded grid">
    <div class="sixteen wide column">
        <div  class="ui segment grid">
            <div class="sixteen wide column">
                <h3>{{ job.position|upper }}<small class="rght">{{ job.created }}</small></h3>
                <div class="ui divider"></div>
                <h4 class="ui red header">от {{ job.min_rate }} до {{ job.max_rate }} руб.</h4>
                <p><strong>Регион: </strong> {{ job.area }}</p>
                <strong>График: </strong>
                {% for s in job.shedule.all %}
                    <div class="ui medium blue label">{{ s }}</div>
                {% endfor %}
                <br></br>
                <!--<strong>Описание: </strong>
                <br></br>-->
                <p>{{ job.description|safe }}</p>
                <div class="ui divider"></div>
                <form id="reply_form" method="POST">
                    {% csrf_token %}
                    <input id="id_vacancy" type="hidden" name="vacancy" value="{{ job.id }}"/>
                    {% if not replies.count >= 1 %}
                    <button id="for_filled_check_job" type="submit" class="ui small green button">Откликнуться</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

jobs/templates/jobs.html
{% extends "basis.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load pagination_tags %}
{% load user_aid %}

{% block extend_header %}
<script src="{% static 'js/form.js' %}"></script>
<script src="{% static 'js/moment.js' %}"></script>
<script src="{% static 'js/validation.js' %}"></script>

{% endblock %}

{% block content %}
<div class="vac-list-wrap">
      <div class="container">
          <div class="row">
                <div class="col-md-12">
                    <!--<div class="redact text-center"><a href="javascript:void(0)">Форма поиска</a></div>-->
                    <form action="" method="get" class="filter">
                        <div class="row">
                            <div class="col-md-5 form-inline">

                                <label for="id_position">Позиция:</label>
                                {{ jobs.form.position|add_class:"ui search selection dropdown" }}

                              </div>
                            <div class="col-md-1 form-inline">
								
                                {{ jobs.form.rotational }}
								<label id="for_rot" for="id_rotational"><span id="span_rot">Вахта:</span></label>
                            </div>
							<div class="col-md-6 form-inline">
                                <label for="id_region">Регион:</label>
                                {{ jobs.form.area|add_class:"ui search selection dropdown" }}
								<script type="text/javascript">
                                   
                                </script>
                            </div>
                            <!--<div class="col-md-6">
                                <label for="id_shedule">График:</label>
                                {{ jobs.form.shedule|add_class:"ui dropdown" }}
                            </div>-->
                        </div>
                        <div class="row mrg">
                            <div class="col-md-4">
                                {{ jobs.form.max_rate__gte|attr:"type:text"|add_class:"form-control custom-form-control"|attr:"placeholder:Уровень дохода от"}}
                            </div>
                            <div class="col-md-4">
                                <!--{{ jobs.form.min_rate__lte|attr:"type:text"|add_class:"form-control custom-form-control"|attr:"placeholder:Уровень дохода до" }}-->
                            </div>
                            <div class="col-md-4">
                                <button type="submit" class="find">Искать</button>
                            </div>
                        </div>
                    </form>
					<hr class="hr-dotted"/>
                </div>
                {% autopaginate jobs.qs 10 as vac%}
                <div class="col-md-12">
                    <div class="vac-list-title text-center">Количество подходящих вакансий: {{ jobs.count }}</div>
                </div>
            </div>
      </div>
        
        <div class="vac-list">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% for v in vac %}
                        <div class="vacitem">
                            <div class="head">
								<div class="name"><!--<img src="static/img/vac-list-icon.jpg" alt="">--><span><a href="jobs/{{ v.id }}">{{ v.position|upper }}</a></span></div> 
                                <div class="published">{% if v.urgent %}СРОЧНАЯ{% endif %}</div>
                            </div>
                            <div class="info">
                                <div class="top-info">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="money">
                                                от <strong>{{ v.min_rate }}</strong> до <strong>{{ v.max_rate }}</strong>  за месяц
                                            </div>
                                        </div>
                                        <div class="col-md-3 text-center">
                                            <span>Регион:</span> {{ v.area }}   
                                        </div>
                                    </div>
                                </div> 
                                <div class="schedule">
                                    <span>График работы:</span> {% for s in v.shedule.all %}{{ s }}{% endfor %}
                                </div>   
                            </div>
                            <div class="bottom-vac">
                                <div class="col-md-4">
                                  {% if user.is_authenticated %}
                                    <form id="reply_form" method="POST">
                                      {% csrf_token %}
                                        <input id="id_vacancy" type="hidden" name="vacancy" value="{{ v.id }}"/>
                                      
                                        {% if not replies.count >= 1 %}
                                        <button type="submit" class="apply" id="for_filled_check_jobs">Подать заявку</button>
                                        {% else %}
                                        <button type="button" class="apply cancel_modal" data-toggle="modal" data-id="{{ v.id }}" data-target="#myModal">Подать заявку</button>
                                        {% endif %}
                                    </form>
                                  {% else %}
                                  <h4>Вы должны <a href="signup/">зарегистрироваться</a> для того, чтобы подать заявку.</h4>
                                  {% endif %}
                                </div>
                                <div class="col-md-3 text-center">
                                    <a href="jobs/{{ v.id }}" class="more">Подробнее о позиции</a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                        {% endfor %}
    </div>
</div>
        </div>
        </div>
                {% paginate %}

	{% include "cancel_modal.html" %}
{% endblock %}
		{% block scripts %}
		  <script src="{% static 'js/jobs.js' %}"></script>
	{% endblock %}
<div class="ui pagination menu">
            {% if page.has_previous %}
            <a class="item" href="?page={{ page.previous_page_number}}"><</a>
            {% endif %}
            {% for p in pages.page_range %}
                {% if p == page.number %}
                    <a href="/jobs?page={{p}}" class="active item">{{ p }}</a>
                {% else %}
                    <a href="/jobs?page={{p}}" class="item">{{ p }}</a>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <a class="item" href="?page={{ page.next_page_number}}">></a>
            {% endif %}
        </div>
<form class="ui form" action="" method="get">
            <div class="fields">
                <div class="four wide field">
                    
                </div>
                <div class="four wide field">
                    <label for="id_region">Регион:</label>
                    {{ jobs.form.area|add_class:"ui search selection dropdown" }}
                </div>
                <div class="eight wide field">
                    <label for="id_shedule">График:</label>
                    {{ jobs.form.shedule|add_class:"ui dropdown" }}
                </div>
            </div>
            <div class="fields">
                <div class="eight wide field">
                    <label for="id_rate">Уровень компенсации:</label>
                    <div class="two fields">
                        <div class="field">
                            {{ jobs.form.max_rate__gte|attr:"type:text"|attr:"placeholder:от" }}
                        </div>
                        <div class="field">
                            {{ jobs.form.min_rate__lte|attr:"type:text"|attr:"placeholder:до" }}
                        </div>
                    </div>
                </div>
                <div id="filter_adj" class="four wide field">
                    <input class="ui small primary button" type="submit" value="Поиск"/>
                    <a class="ui small red button" href="jobs">Очистить</a>
                </div>
            </div>
        </form>
{% if page_obj.has_previous %}
<li><a href="?page{{ page_suffix }}={{ page_obj.previous_page_number }}{{ getvars }}{{ hashtag }}"><img src="static/img/arr-prev.jpg" alt=""></a></li>
{% endif %}
                {% for page in pages %}
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <li class="active"><a href="#">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?page{{ page_suffix }}={{ page }}{{ getvars }}{{ hashtag }}">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="active">...</li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="?page{{ page_suffix }}={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}"><img src="static/img/arr-next.jpg" alt=""></a></li>
                {% endif %}

jobs/templates/notifications.html
{% extends "basis.html" %}
{% load l10n %}

{% block content %}
<div class="vac-list-wrap">
       <div class="vac-list">
            <div class="container">
                    <div class="col-md-12">
                      {% if notifications.count < 1 %}
                         <div class="sixteen wide center aligned column">
                            <h3 class="ui red header">Уведомлений пока нет.</h3>
                         </div>
                      {% else %}
                        {% for n in notifications %}
                        
                        <div class="vacitem">
                            <div class="head">
                                <div class="name"><!--<img src="static/img/vac-list-icon.jpg" alt="">--><span>{{ n.created }}</span> {% if n.new %}<a class="ui orange empty circular label"></a>{% endif %}</div> 
                                <!--<div class="published">{{ v.created }}</div>-->
                            </div>
                            <div class="info">
                                <div class="top-info">
                                    <div class="row">
                                        
                                        <div class="col-md-12">
                                            {{ n.text | safe }}   
                                        </div>
                                    </div>
                                </div>   
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
              </div>
        </div>
</div>
{% endblock %}

<div class="ui padded grid">
    <div class = "sixteen wide center aligned column">
        <h1 class="ui header">УВЕДОМЛЕНИЯ</h1>
        <div class="ui divider"></div>
    </div>
    {% if notifications.count < 1 %}
    <div class="sixteen wide center aligned column">
        <h3 class="ui red header">Уведомлений пока нет.</h3>
    </div>
    {% else %}
    <div class="sixteen wide column">
        {% for n in notifications %}
        <div  class="ui segment grid">
            <div class="sixteen wide column">
                <h3>{{ n.created }}</h3>
                <div class="ui divider"></div>
                <p>{{ n.text | safe }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

jobs/templates/regions_list.html
{% for r in regions %} 
  <option value="{{ r.id }}">{{ r.area }}</option>
{% endfor %}

jobs/templates/replies.html
{% extends "basis.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<div class="vac-list-wrap">
       <div class="vac-list">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% for r in replies %}
                        <div class="vacitem">
                            <div class="head">
                                <div class="name"><!--<img src="static/img/vac-list-icon.jpg" alt="">--><span>{{ r.vacancy.position|upper }}</span></div> 
                                <!--<div class="published">{{ v.created }}</div>-->
                            </div>
                            <div class="info">
                                <div class="top-info">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="money">
                                                от <strong>{{ r.vacancy.min_rate }}</strong> до <strong>{{ r.vacancy.max_rate }}</strong>  за месяц
                                            </div>
                                        </div>
                                        <div class="col-md-3 text-center">
                                            <span>Регион:</span> {{ r.vacancy.area }}   
                                        </div>
                                    </div>
                                </div> 
                                <div class="schedule">
                                    <span>График работы:</span> {% for s in r.vacancy.shedule.all %}{{ s }}{% endfor %}
                                </div>   
                            </div>
                            <div class="bottom-vac">
                                <div class="col-md-4">
                                  {% if r.active %}
                                  <button id="for_filled_check_reply" onclick="window.location.href='reply/delete/{{ r.id }}'" class="apply">Отозвать</button>
                                  {% else %}
                                  <button class="apply disabled" onclick="return false;">Отозвана</button>
                                  {% endif %}
                                </div>
                                <!--<div class="col-md-3 text-center">
                                    <a href="jobs/{{ r.vacancy.id }}" class="more">Подробнее о позиции</a>
                                </div>-->
                                <div class="clear"></div>
                            </div>
                        </div>
                        {% endfor %}
    </div>
</div>
        </div>
        </div>
{% endblock %}

<div class="ui padded grid">
    <div class = "sixteen wide center aligned column">
        <h1 class="ui header">МОИ ЗАЯВКИ</h1>
        <div class="ui divider"></div>
    </div>
    <div class="sixteen wide column">
        {% for r in replies %}
        <div  class="ui {% if not r.active %}disabled{% endif %} segment grid">
            <div class="sixteen wide column">
                <h3>{{ r.vacancy.position|upper }}
                    {% if r.active %}
                    {% if r.status.id == 1 %}
                        <div class="ui olive label">{{ r.status }}</div>
                    {% elif r.status.id == 0 %}
                        <div class="ui green label">{{ r.status }}</div>
                    {% elif r.status.id == 8 %}
                        <div class="ui red label">{{ r.status }}</div>
                    {% else %}
                        <div class="ui yellow label">{{ r.status }}</div>
                    {% endif %}
                    {% endif %}
                    <small class="rght">{{ r.created }}</small>
                </h3>
                <div class="ui divider"></div>
                <h4 class="ui red header">от {{ r.vacancy.min_rate }} до {{ r.vacancy.max_rate }} {{ r.vacancy.rate_type }}</h4>
                <p><strong>Регион: </strong> {{ r.vacancy.area }}</p>
                <strong>График: </strong>
                {% for s in r.vacancy.shedule.all %}
                    <div class="ui medium blue label">{{ s }}</div>
                {% endfor %}
                <br></br>
                <!--<strong>Описание: </strong>
                <br></br>-->
                <p>{{ r.vacancy.description|safe|truncatechars_html:195 }}</p>
                <div class="ui divider"></div>
                {% if r.active %}<a href="reply/delete/{{ r.id }}" class="ui small red button">Отозвать</a>{% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>